CC = gcc

obj = lexico.o fila.o sintatico.o

trabalho_1: $(obj)
	$(CC) $(obj) -o trabalho_1 -lm

lexico.o: lexico.c  
	$(CC) -c lexico.c

fila.o: fila.c  
	$(CC) -c fila.c

sintatico.o: sintatico.c  
	$(CC) -c sintatico.c
